# 应用服务 WEB 访问端口
server:
  port: 8090

spring:
  # 应用名称
  application:
    name: CRAN
  datasource:
    # 数据库驱动：
    driver-class-name : com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/cran?serverTimezone=GMT%2b8
    # 数据库用户名&密码：
    username: root
    password: 123456

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #指定Mybatis的实体目录
  type-aliases-package: com.example.cran.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



